# packages from canonical repository
brew 'autojump'
brew 'fzf'
brew 'git'
brew 'imagemagick'
brew 'macvim', args: ['override-system-vim']
brew 'phantomjs'
brew 'postgresql'
brew 'rbenv'
brew 'rbenv-gem-rehash'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vimpager'
brew 'zsh'

tap 'thoughtbot/formulae'
brew 'gitsh'
brew 'rcm'
