# packages from canonical repository
brew 'autojump'
brew 'chromedriver'
brew 'coreutils'
brew 'git'
brew 'imagemagick'
brew 'most'
brew 'mysql'
brew 'node'
brew 'openssl'
brew 'phantomjs'
brew 'postgis'
brew 'postgresql'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'shellcheck'
brew 'sqlite'
brew 'ripgrep'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'jq'

tap 'petere/postgresql'
brew 'postgresql-common'

tap 'thoughtbot/formulae'
brew 'rcm'

# quicklook plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlimagesize'
cask 'webpquicklook'
