#!usr/bin/env sh

echo "Installing Padde’s dotfiles..."

ln -vs ~/.dotfiles/gem/gemrc ~/.gemrc
ln -vs ~/.dotfiles/git/gitconfig ~/.gitconfig
ln -vs ~/.dotfiles/git/gitignore ~/.gitignore
ln -vs ~/.dotfiles/input/inputrc ~/.inputrc
ln -vs ~/.dotfiles/irb/irbrc ~/.irbrc
ln -vs ~/.dotfiles/latexmk/latexmkrc ~/.latexmkrc
ln -vs ~/.dotfiles/vim/vimrc ~/.vimrc
ln -vs ~/.dotfiles/vim/vim/ ~/.vim
ln -vs ~/.dotfiles/zsh/zsh/ ~/.zsh
ln -vs ~/.dotfiles/zsh/zshrc ~/.zshrc
ln -vs ~/.dotfiles/zsh/oh-my-zsh/ ~/.oh-my-zsh

echo "Done."
