set nocompatible      " We're running Vim, not Vi!
set number
set noshowmatch
set nowrap
set visualbell

set expandtab         " i like soft tabs
set shiftwidth=2
set softtabstop=2

set mouse=a           " mouse support

syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins

if has('mac')         " Share clipboard on osx
set clipboard+=unnamed
endif

" key mappings
map <S-Enter> O<Esc>
map <CR>      o<Esc>

" aliases
command Wsudo :w !sudo tee %
