#!/bin/bash
# Warn before pushing to protected branches
# Bypass with git push --no-verify
# Adapted from https://gist.github.com/Hammadk/0a196dd1ac5ad971df1a

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(master|production|staging|integration)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
  read -p "Are you sure you want to push to $BRANCH? [Yn] " -r < /dev/tty
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    exit 0
  fi
  echo "aborted"
  exit 1
fi
exit 0
