# /usr/local/bin should be in front of /usr/bin for homebrew
export PATH=/usr/local/bin:$PATH

# Add RVM to PATH for scripting
PATH=$PATH:$HOME/.rvm/bin 

# Heroku Toolbelt
HEROKU_TOOLBELT_DIR="/usr/local/heroku/bin"
if [ -d "$HEROKU_TOOLBELT_DIR" ]; then
  export PATH="$HEROKU_TOOLBELT_DIR:$PATH"
fi

# TeX live
TEX_BIN_DIR="/usr/texbin"
if [ -d "$TEX_BIN_DIR" ]; then
  export PATH="$TEX_BIN_DIR:$PATH"
fi

# Pick up npm Libraries
NODE_MODULES_DIR="/usr/local/lib/node_modules"
if [ -d "$NODE_MODULES_DIR" ]; then
  export NODE_PATH=NODE_MODULES_DIR
  export PATH="/usr/local/share/npm/bin:$PATH"
fi
