# Load RVM Function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# Pick up npm Libraries
NODE_PATH=/usr/local/lib/node_modules
