# Custom directory outside of ~/.oh-my-zsh/ so we can track it with git
ZSH_CUSTOM="$HOME/.dotfiles/zsh/custom/"

# Prevent oh-my-zsh from asking for updates
# (use update_dotfiles instead and commit changes)
DISABLE_AUTO_UPDATE="true"

# Path to oh-my-zsh conf
ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME="padde"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Plugins
plugins=(brew bundler gem git github osx rails3 ruby rvm)

source $ZSH_CUSTOM/lib/hg.zsh

# OH MY ZSH!
source $ZSH/oh-my-zsh.sh

# use macvim binary (has clipboard support)
if [[ -d /Applications/MacVim.app ]]; then
  # alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
  alias vim=mvim
elif [[ -d ~/Applications/MacVim.app ]]; then
  # alias vim='~/Applications/MacVim.app/Contents/MacOS/Vim'
  alias vim=mvim
fi

# fix history search 
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward 

# Use most as pager, if available
if most -v &> /dev/null; then
  PAGER=most
fi

# colorize listings (especially in `tree`)
LS_COLORS="no=00:di=34:ln=35:so=33"
LS_COLORS="ex=37;41:$LS_COLORS"
LS_COLORS="*.zip=36:*.rar=36:*.tar=36:*.gz=36:*.tar.gz=36:*.7z=36:$LS_COLORS"
LS_COLORS="*.c=32:*.cc=32:*.cpp=32:*.m=32:*.rb=32:*.pl=32:*.php=32:*.java=32:$LS_COLORS"
LS_COLORS="*.h=33:*.hpp=33:$LS_COLORS"
LS_COLORS="*.o=30:*.d=30:$LS_COLORS"
LS_COLORS="*Makefile=35:*.mk=35:*Rakefile=35:$LS_COLORS"
export LS_COLORS

# heroku toolbelt
HEROKU_TOOLBELT_DIR="/usr/local/heroku/bin"
if [ -d "$HEROKU_TOOLBELT_DIR" ]; then
  export PATH="$HEROKU_TOOLBELT_DIR:$PATH"
fi
