# Custom directory outside of ~/.oh-my-zsh/ so we can track it with git
ZSH_CUSTOM="$HOME/.dotfiles/zsh/custom/"

# Prevent oh-my-zsh from asking for updates
# (use update_dotfiles instead and commit changes)
DISABLE_AUTO_UPDATE="true"

# Path to oh-my-zsh conf
ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME="padde"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Plugins
plugins=(brew bundler gem git github osx rails3 ruby rvm)

# OH MY ZSH!
source $ZSH/oh-my-zsh.sh

# Load RVM Function
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# Pick up npm Libraries
NODE_PATH=/usr/local/lib/node_modules

# use macvim binary (has clipboard support)
if [[ -d /Applications/MacVim.app ]]; then
  # alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
  alias vim=mvim
elif [[ -d ~/Applications/MacVim.app ]]; then
  # alias vim='~/Applications/MacVim.app/Contents/MacOS/Vim'
  alias vim=mvim
fi

# fix history search 
bindkey '\e[A' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward 
